// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "danial.6274@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/product": {
            "post": {
                "description": "CreateProduct",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "CreateProduct",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_internal_app_routerHandler_product_dto.CreateProductRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.Product"
                        }
                    }
                }
            }
        },
        "/api/v1/product-revision/{productId}": {
            "get": {
                "description": "GetProductRevisions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Revision"
                ],
                "summary": "GetProductRevisions",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "Product Id",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/productRevisionDto.ProductRevisionsListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/product/{id}": {
            "get": {
                "description": "GetProduct",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "GetProduct",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "Product Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.Product"
                        }
                    }
                }
            },
            "put": {
                "description": "UpdateProduct",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "UpdateProduct",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_internal_app_routerHandler_product_dto.CreateProductRequestDto"
                        }
                    },
                    {
                        "type": "string",
                        "format": "string",
                        "description": "Product Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.Product"
                        }
                    }
                }
            }
        },
        "/api/v1/product/{id}/revision/{revisionId}": {
            "get": {
                "description": "GetProductByRevisionId",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "GetProductByRevisionId",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "Product Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "string",
                        "description": "Revision Id",
                        "name": "revisionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.Product"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_DaniaLD_upera-go-test_internal_app_routerHandler_product_dto.CreateProductRequestDto": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "imageURL": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "github_com_DaniaLD_upera-go-test_pkg_model.Product": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageURL": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_DaniaLD_upera-go-test_pkg_model.ProductRevision": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "newValue": {
                    "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.Product"
                },
                "previousValue": {
                    "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.Product"
                },
                "productId": {
                    "type": "string"
                },
                "revisionId": {
                    "type": "integer"
                },
                "updatedAttributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "productRevisionDto.ProductRevisionsListResponse": {
            "type": "object",
            "properties": {
                "revisions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_DaniaLD_upera-go-test_pkg_model.ProductRevision"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Upera - Product Versioning",
	Description:      "This is an assessment for Upera company",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
